### ISSUE TITLE
TypeError or $TypeError ?

### ISSUE THREAD

**Issue by motla** [ljharb/es-abstract#107]
Hi!

Line 36 should probably rather be `new $TypeError` like on line 43.

https://github.com/ljharb/es-abstract/blob/599961920d3b977df94527601772e19cee1474fe/2019/ToPropertyDescriptor.js#L33-L46

It appears in every `ToPropertyDescriptor.js`, and also you can search the project for `"new TypeError"`, it appears without the `$` in files `NumberToString.js` and `CopyDataProperties.js` as well.

**Comment by ljharb** [comment]
Thanks, will be fixed in the next version :-)
