### ISSUE TITLE
SES-shim Compat - Assigning to 'apply' to a fn is not permitted

### ISSUE THREAD

**Issue by kumavis** [ljharb/es-abstract#112]
This assignment of `apply` on to `module.exports` throws an error under the ses-shim

https://github.com/ljharb/es-abstract/blob/67a1a94ee9c9b36d7505c0eac0e2b95a2811e5e4/helpers/callBind.js#L15

A non-breaking solution would be to append the export via `Reflect.defineProperty` instead of assignment

**Comment by kumavis** [comment]
as a breaking change, you could have the module export `{ call, apply }` without overwriting `callBind`'s apply fn

**Comment by kumavis** [comment]
maybe thats bug worthy on its own, the exported `callBind` fn is not called when attempted to be called via `callBind.apply(...)`

**Comment by ljharb** [comment]
I think that it's reasonable to use https://github.com/ljharb/es-abstract/blob/master/helpers/DefineOwnProperty.js instead of assignment - I don't think a breaking change is warranted.
