### ISSUE TITLE
ToInteger(-0) returns -0, but spec says it should return +0

### ISSUE THREAD

**Issue by justingrant** [ljharb/es-abstract#116]
According to https://tc39.es/ecma262/#sec-tointeger:

> If number is NaN, +0, or -0, return +0.

But:

```js
import ToInteger from 'es-abstract/2019/ToInteger.js';
ToInteger(-0).toLocaleString();
// expected: "0"
// actual: "-0"
```

Live repro: https://codesandbox.io/s/awesome-framework-nvwgw?file=/src/index.js

**Comment by ljharb** [comment]
in ES2019, ToInteger(-0) does return -0: https://www.ecma-international.org/ecma-262/10.0/#sec-tointeger

This changed in ES2020: https://www.ecma-international.org/ecma-262/11.0/#sec-tointeger

If you `npm install es-abstract@next`, and import from the 2020 operations, you'll see that behavior.

**Comment by justingrant** [comment]
Ahhh, got it.  Mystery solved for 2019.  But the 2020 implementation returns the same result:

```js
import ToInteger from 'es-abstract/2020/ToInteger.js';
ToInteger(-0).toLocaleString();
// expected: "0"
// actual: "-0"
```

Is `1.18.0-next.0` the expected version?

```
  "dependencies": {
    "es-abstract": "1.18.0-next.0"
  },
```

BTW I updated the live repro at https://codesandbox.io/s/awesome-framework-nvwgw?file=/src/index.js to use the 2020 import.

**Comment by ljharb** [comment]
Yes, it is - and in that case, that's a bug :-) On it.

**Comment by justingrant** [comment]
Thanks for blazing-fast turnaround! ;-)

**Comment by ljharb** [comment]
I’ll have another prerelease out tonight,

**Comment by justingrant** [comment]
> I’ll have another prerelease out tonight.

Hi @ljharb - Is there a new ETA for this release?  Asking because I have some time today to work on Temporal and want to figure out if it's worth a temporary checkin to work around this bug, or to just wait.

**Comment by ljharb** [comment]
My bad, I'll be publishing it within the hour.

**Comment by ljharb** [comment]
v1.18.0-next.1 has been released.
