### ISSUE TITLE
Reduce the size of this package?

### ISSUE THREAD

**Issue by cpojer** [ljharb/es-abstract#118]
I noticed this package showed up in several very small packages, like `object.assign` which only use two methods from this `es-abstract`. Would it be possibly to split this package up into several smaller ones so that consumers do not have to pay the cost of 4 MiB for this package, which is possibly duplicated due to semver ranges on the small packages that depend on it already?

**Comment by ljharb** [comment]
What cost are you referring to? Bundle size, and memory footprint, will be tiny if only two methods are used - the disk size of a few hundred K, or the install size of a few gzipped K surely isn’t a concern?

Separately, most parts of this package are all interconnected; there’s very little that could be split out.

**Comment by cpojer** [comment]
I'm referring to disk size of the package, which is about 4 MiB in `node_modules`. This package alone is as big as eslint, and accounts for about 4% of the entire `node_modules` size for React Native at Facebook, even though we are only pulling it in through very small intermediary packages between `eslint-plugin-react`/`eslint-plugin-jsx-a11y` and this one. Alternatively, could we change `eslint-plugin-react` not to transitively depend on `es-abstract`? Some of the provided functionality, and `object.assign` in particular, have been part of node since 4.0.

**Comment by ljharb** [comment]
Certainly eslint-plugin-react requires node 4 now, so it could drop the `object.assign` dependency; feel free to submit a PR doing that.

I will point out tho that it seems highly likely, given Babel's plans, that in the coming year you might end up depending on es-abstract via a great many packages, so the collective weight won't be as much of a problem. That said, `object.assign` does only depend on `GetIntrinsic`, `callBind`, and `callBound` from `es-abstract`, so those parts of it actually are entirely separable into their own packages. I'll look into doing that anyways.

**Comment by ljharb** [comment]
I've published https://npmjs.com/get-intrinsic and https://npmjs.com/call-bind, and updated es-abstract to use them in 0f051dc and 63bc9ad, and also published v4.1.2 of `object.assign` which uses them and drops es-abstract as a dependency.

That doesn't make _this_ package any smaller, but it should hopefully address your current concern.
