### ISSUE TITLE
Folder 2020 is not existing anymore in version 1.17.7

### ISSUE THREAD

**Issue by antonpatotski** [ljharb/es-abstract#120]
Folder 2020 is not existing anymore in version 1.17.7

I download this package by zip file from https://github.com/ljharb/es-abstract/releases

**Comment by ljharb** [comment]
It has in fact never existed - it’s only in v1.18 (of which there’s only prereleases right now).

Please don’t download things from GitHub to use them; npm packages should be consumed via npm install.
