### ISSUE TITLE
Why is operations/2020.js ignored ?

### ISSUE THREAD

**Issue by guimard** [ljharb/es-abstract#125]
Hi,
in version 1.18.0-next.2, files `operations/201*.js` are installed but `operations/2020.js` is ignored in `.npmignore`, why ?

**Comment by ljharb** [comment]
It's an oversight. Do you need the operations list for something? In the next major I intend to ignore all of them.

**Comment by guimard** [comment]
Hi, for [Debian](https://debian.org) packaging: I have to:
* reproduce upstream build with and without test
* enable "autopkgtest": this means that our tool _(`pkg-js-tools/dh-sequence-nodejs`)_ tries to launch upstream test using installed files. That's how I found this oversight:
  * [Failing autopkgtest](https://salsa.debian.org/js-team/node-es-abstract/-/jobs/1379480)
  * [Fix](https://salsa.debian.org/js-team/node-es-abstract/-/blob/master/debian/patches/install-2020.patch)
  * [Successful autopkgtest](https://salsa.debian.org/js-team/node-es-abstract/-/jobs/1379561)

Cheers,
Xavier

**Comment by ljharb** [comment]
Understood. I would prefer Debian not package my software - Debian users, like the rest of the internet, should npm install it.
