### ISSUE TITLE
Possible Problems with Your NPM Repository?

### ISSUE THREAD

**Issue by kling-appfire** [ljharb/es-abstract#128]
Latest version on your [npm listing](https://www.npmjs.com/package/es-abstract) has 0 downloads tracked for last 7d and every dependency (i.e. @npmcli/arborist specifically) throws:

» npm i es-abstract
npm ERR! code ETARGET
npm ERR! notarget No matching version found for es-abstract@^1.18.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ljharb** [comment]
What does `npm config get registry` show?

Download counts are typically updated daily, so I'd expect both of the versions published today to have 0 downloads until tomorrow.

**Comment by ljharb** [comment]
You can see on https://unpkg.com/es-abstract/ that v1.18.2 and v1.18.1 work just fine (that site fetches straight from the registry) so I'm confident it's not an issue with this package.

**Comment by kling-appfire** [comment]
Thank you and sorry to bother. I cleared the cache of our nexus repo proxy. that was it.
