### ISSUE TITLE
version 1.18.2 causing npm install to fail when using node 6

### ISSUE THREAD

**Issue by siklign** [ljharb/es-abstract#129]
Hi,

Our project is using
node v6.1.0
npm  v3.8.6

Since es-abstract v1.18.2 was released, npm install is failing for us - see verbose output below:
npm http 304 https://artifactory.imperva.com/api/npm/npm-repos/es-abstract
npm verb headers { date: 'Wed, 26 May 2021 06:31:01 GMT',
npm verb headers   server: 'Artifactory/7.9.1 70901900',
npm verb headers   connection: 'Keep-Alive',
npm verb headers   'keep-alive': 'timeout=5, max=84',
npm verb headers   etag: '5f4e6585739b46adcb26124e304c0b562c10de47' }
npm verb etag https://artifactory.imperva.com/api/npm/npm-repos/es-abstract from cache
npm verb get saving es-abstract to /Users/temanih/workspace/server/gulp/.npm-cache/artifactory.imperva.com/api/npm/npm-repos/es-abstract/.cache.json
npm verb correctMkdir /Users/temanih/workspace/server/gulp/.npm-cache correctMkdir not in flight; initializing
npm verb stack Error: Missing required argument #1
npm verb stack     at andLogAndFinish (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm verb stack     at fetchPackageMetadata (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm verb stack     at resolveWithNewModule (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm verb stack     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:456:7
npm verb stack     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb stack     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm verb stack     at addRequestedAndFinish (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm verb stack     at returnAndAddMetadata (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm verb stack     at pickVersionFromRegistryDocument (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm verb stack     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb cwd /Users/temanih/workspace/server/gulp
npm ERR! Darwin 18.7.0
npm ERR! argv "/Users/temanih/.nvm/versions/node/v6.1.0/bin/node" "/Users/temanih/.nvm/versions/node/v6.1.0/bin/npm" "install" "-verbose"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG
npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /Users/temanih/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

We noticed that you have a failing test that seems related to it also: 
https://github.com/ljharb/es-abstract/runs/2668795707?check_suite_focus=true

When can this be fixed?

Many tahnks

**Comment by ljharb** [comment]
It’s a problem with your private registry (artifactory). I’m confident if you install it from the actual npm registry it will work fine (tests run on node down to 0.8)
