### ISSUE TITLE
Deprecation warning DEP0148 from exports

### ISSUE THREAD

**Issue by crystalfp** [ljharb/es-abstract#135]
Today, after upgrading various packages, running eslint on my project I received plenty of DeprecationWarnings like the following:
```
(node:27812) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the
"exports" field module resolution of the package at <my project>\node_modules\es-abstract\package.json.
Update this package.json to use a subpath pattern like "./2020/*".
```
Same warning for `"./helpers/"` export.
I don't use directly your package. It is called by `eslint-plugin-import@2.23.4` 
The problem is that these messages obscure the real eslint messages.
I tried to implement the suggested correction, but eslint does not work anymore.
Could you take a look at this problem? Thanks!
mario

Windows 10, node 16.4.0, eslint 7.32.0, npm 7.20.3

**Comment by ljharb** [comment]
Duplicate of #133
