### ISSUE TITLE
version mismatch in npm registry and during npm install

### ISSUE THREAD

**Issue by ChandranshuKumar** [ljharb/es-abstract#142]
NPM registry says es-abstract latest version is `1.19.1` but when installed with `npm install` it installs `1.18.6`. Due to this, all the packages which use es-abstract internally are failing to install:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for es-abstract@^1.19.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by ljharb** [comment]
The implication is that you're using a private registry that's sorely outdated.
