### ISSUE TITLE
Version 1.20.2 is missing the  CheckObjectCoercible.js file in Windows 11

### ISSUE THREAD

**Issue by oschina** [ljharb/es-abstract#145]
My OS is Windows 11 with node(18.9.0), npm 8.4.0, yarn 1.22.18

when execute:

`yarn add es-abstract`  

get es-abstract version 1.20.2 , in directory 5 , CheckObjectCoercible.js not found

then

```
yarn remove es-abstract
yarn add es-abstract@1.20.1
```
CheckObjectCoercible.js exists .

so with newest version , i get the follow error:

```
Error: Cannot find module '../5/CheckObjectCoercible'
```

**Comment by ljharb** [comment]
Seems there to me: https://unpkg.com/browse/es-abstract@1.20.2/5/CheckObjectCoercible.js

Perhaps it’s yarn - have you tried with actual npm?

**Comment by oschina** [comment]
> Seems there to me: https://unpkg.com/browse/es-abstract@1.20.2/5/CheckObjectCoercible.js
> 
> Perhaps it’s yarn - have you tried with actual npm?

Yes, i use yarn, don't try npm

finally, i use this config to bypass this version:

```
"resolutions": {
    "es-abstract": "1.20.1"
}
```

**Comment by ljharb** [comment]
You shouldn’t have to, the file is there and it works fine. Please try npm to figure out if yarn is the problem.

‘In the meantime, ill close this, since it’s not a problem with the package.

**Comment by oschina** [comment]
> You shouldn’t have to, the file is there and it works fine. Please try npm to figure out if yarn is the problem.
> 
> ‘In the meantime, ill close this, since it’s not a problem with the package.

ok, i have try npm, it works.
It's so weird, why yarn not, and only 1.20.2 not work.

**Comment by ljharb** [comment]
No idea, you should file a bug on yarn though if it’s not fixed in a later yarn 1 version.
