### ISSUE TITLE
available-typed-arrays should be in dependencies, not devDependencies

### ISSUE THREAD

**Issue by fulviociapessoni** [ljharb/es-abstract#148]
Last version 1.21.0 has a new devDependencies `available-typed-arrays@^1.0.5`, this is a problem because some package manager don't install devDependencies.
Please change this as dependency.

**Comment by ljharb** [comment]
All package managers don't :-) thanks, will be fixed shortly.

**Comment by ljharb** [comment]
Fixed in c18ed51, and released in v1.21.1
