### ISSUE TITLE
 DeprecationWarning after update to Node 16v.

### ISSUE THREAD

**Issue by Clasen00** [ljharb/es-abstract#149]
Hello, thank you for your job!
Once we had updated from node 14 to node 16 there is appear a deprecation warning:
```
(node:33529) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /frontend/app/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
How may I fix that?

**Comment by ljharb** [comment]
You can't; it would require this package to do a breaking change, or to remove the "exports" field, neither of which is planned. You'll just need to ignore it.
