### ISSUE TITLE
`UTF16Decode`, `CodePointAt`, and related operations return strings instead of numbers

### ISSUE THREAD

**Issue by mhassan1** [ljharb/es-abstract#150]
Currently, the implementations of the following operations return strings, but they should return numbers (for example, https://tc39.es/ecma262/#sec-utf16decodesurrogatepair):
* `UTF16SurrogatePairToCodePoint`
* `UTF16DecodeSurrogatePair`
* `UTF16Decode`
* `UTF16DecodeString`
* `CodePointAt`
* `StringToCodePoints`

**Comment by ljharb** [comment]
CodePointAt returns a Record, and strings basically *are* code points (the [[CodePoint]] field). What value would you expect there?

**Comment by mhassan1** [comment]
The description of `UTF16SurrogatePairToCodePoint` (below) sets `cp` to a number then returns `cp` (unless we are supposed to interpret `Return the code point cp.` as `Return the code point whose numeric value is that of cp.`).

> 2. Let cp be (lead - 0xD800) × 0x400 + (trail - 0xDC00) + 0x10000.
> 3. Return the code point cp.

Maybe this is just a matter of interpretation of what a code point could be (a number or a string), but I thought it was supposed to be a number.

**Comment by mhassan1** [comment]
I think part of the confusion is that `String.prototype.codePointAt` returns a number:

> 7. Return [𝔽](https://tc39.es/ecma262/#%F0%9D%94%BD)(cp.[[CodePoint]]).

For that reason, "code point" feels like a number, but I agree that the spec isn't explicit about that. FWIW, [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Code_point) also says it's a number, but I guess that's talking about the `String.prototype.codePointAt` result, not necessarily the abstract "code point."

I don't have a use case where it makes a difference. I just found it confusing while I was implementing a polyfill for `String.prototype.toWellFormed`. For example, `UTF16EncodeCodePoint` has this:

> 2. If cp ≤ 0xFFFF, return the String value consisting of the code unit whose numeric value is cp.

Again, that `≤` could be interpreted as "the number representing the code point is less than."

**Comment by ljharb** [comment]
do note that https://npmjs.com/string.prototype.towellformed already exists :-p

indeed, `<=` in JS works on both strings and numbers, so that was my interpretation here ras well.

**Comment by mhassan1** [comment]
Understood. Closing this. Thanks!
