### ISSUE TITLE
Remove 'is-negative-zero' library and unused helper functions

### ISSUE THREAD

**Issue by sicin** [ljharb/es-abstract#156]
Since 'math-intrinsics' already has an implementation of isNegativeZero and it's actively being imported in the code, there is no need for 'is-negative-zero', which is no longer imported anywhere, to be a dependency.

Also, some functions in `helpers` folder seem to be unused anywhere in the code, such as isNegativeZero, isNaN, or isInteger.

**Comment by ljharb** [comment]
It would be semver-major to remove those unused helpers, which is why they have a TODO comment to remove them in the next major bump.

you're right about is-negative-zero, though, thanks.
