### ISSUE TITLE
ToNumber not working with Date objects

### ISSUE THREAD

**Issue by Xotic750** [ljharb/es-abstract#27]
https://github.com/ljharb/es-abstract/blob/master/es2015.js#L67

`var value = isPrimitive(argument) ? argument : toPrimitive(argument, 'number');`

seems that it should be

`var value = isPrimitive(argument) ? argument : toPrimitive(argument, Number);`

As according to es-to-primitive, the PreferredType should be `String` or `Number` if supplied.
https://github.com/ljharb/es-to-primitive/blob/master/es6.js#L48

**Comment by ljharb** [comment]
Thanks, good catch.
