### ISSUE TITLE
Reduce size of package

### ISSUE THREAD

**Issue by mrmlnc** [ljharb/es-abstract#29]
Hello, @ljharb,

Would be cool if you exclude `./test` directory and other files from package and publish a new version of your package. That can save more then 180KB for users :)

```
4.0K	.editorconfig
4.0K	.eslintrc
8.0K	.jscs.json
4.0K	.npmignore
4.0K	.nycrc
8.0K	.travis.yml
8.0K	./CHANGELOG.md
4.0K	./LICENSE
4.0K	./Makefile
4.0K	./README.md
 16K	./es2015.js
4.0K	./es2016.js
4.0K	./es2017.js
8.0K	./es5.js
4.0K	./es6.js
4.0K	./es7.js
 24K	./helpers
4.0K	./index.js
 28K	./operations
4.0K	./package.json
172K	./test
```

**Comment by ljharb** [comment]
No thanks; `npm install foo && npm explore foo && npm install && npm test` should always work, and tests (and untranspiled source files, when applicable) should always be published on npm with the package.
