### ISSUE TITLE
Number constructor whitspace handling deficiencies

### ISSUE THREAD

**Issue by Xotic750** [ljharb/es-abstract#3]
See https://github.com/paulmillr/es6-shim/pull/368

**Comment by ljharb** [comment]
I'm confused - how does `ToNumber` interact with `trim`?

**Comment by Xotic750** [comment]
Sorry, probably just my bad language. But what we are talking about here is the internal trimming of whitespace when the Number constructor is used as a casting operator.
`Number('  2  ')`

**Comment by ljharb** [comment]
After implementing the fix for `es6-shim` based on your tests, I totally get it now. Thanks for explaining further!

**Comment by Xotic750** [comment]
You're welcome. ;)
