### ISSUE TITLE
Not able to install version 1.13.0

### ISSUE THREAD

**Issue by jindaliiita** [ljharb/es-abstract#43]

**Comment by ljharb** [comment]
Can you elaborate? "Not able to install" seems like an npm issue; I'm able to install it just fine.

**Comment by KrisNi** [comment]
we ran into this when trying to update enzyme to 3.8.0. the array.prototype.flat package has es-abstract dependency and it says it installed 1.13.0 in npm-shrinkwrap. But when you go into /node_modules/es-abstract changelog. it indicates that it installed 1.7.0 instead of 1.13.0

**Comment by ljharb** [comment]
That suggests it's being duplicated - namely, that you've got multiple copies in your tree. What happens if you run `npm install --no-save enzyme es-abstract array.prototype.flat && npm shrinkwrap`?

**Comment by jindaliiita** [comment]
When I was trying to install version 1.13.0 through NPM, it was giving error **No matching version found for es-abstract@1.13.0**. But now it is working fine.

**Comment by ljharb** [comment]
You might have a private registry or be using a mirror, which might have a long delay for new versions.
