### ISSUE TITLE
isCallable out of date

### ISSUE THREAD

**Issue by Xotic750** [ljharb/es-abstract#5]
https://github.com/ljharb/is-callable/issues/2

**Comment by ljharb** [comment]
Since that's a fix, and this is using semver ranges, `rm -rf node_modules && npm install` should grab the newest one. I'll update the dep explicitly at some point.

**Comment by Xotic750** [comment]
Aha, will try that. I tried a few different things but nothing I did grabbed the latest. Cheers.
