### ISSUE TITLE
es-abstract 1.14.0 no longer exists in npm

### ISSUE THREAD

**Issue by akotranza** [ljharb/es-abstract#55]
Hi, 1.14.0 no longer exists on npm as of a couple hours ago which is blowing up whatever version of webpack I'm using. Will hack around it in package-lock.json, but kind of a problem when versions disappear 😄

**Comment by ljharb** [comment]
Indeed, i apologize for the inconvenience - it hadn’t been 24 hours yet, and it had files in it that it shouldn’t have. v1.14.1 is already published, before i unpublished v1.14.0, so it should be trivial to update it in your lockfile.

**Comment by JakobFels** [comment]
Is it because of the report files accidentally published and the contained env secrets it contained? If so, you should still rotate all your passwords, as people might've cached it (as our company proxy did).

**Comment by ljharb** [comment]
Yes, I’ve already taken care of that, thanks.

**Comment by bj00rn** [comment]
@ljharb maybe add a temporary note to readme about this version being removed, since ppl are still ending up here.

I Didn't get this error until i wiped my yarn cache..

**Comment by ljharb** [comment]
It’d be helpful if someone could help shed light on what package out there is still depending on 1.14.0. This package is on v1.16.0 now.

**Comment by bj00rn** [comment]
> It’d be helpful if someone could help shed light on what package out there is still depending on 1.14.0. This package is on v1.16.0 now.

The problem for me was that I couldn't even do a yarn install once i nuked my cache, since I had 1.14.0 resolved in my lock file. I had to edit the file manually and remove the 'resolved' url. I after that I did a yarn install and yarn set me up with 1.16.1.

**Comment by ljharb** [comment]
Sounds like a bug to file on yarn, as an unpublished package in the lockfile is something that clearly can happen.
