### ISSUE TITLE
Where is v1.14.0 on npm?

### ISSUE THREAD

**Issue by henriquelbsouza** [ljharb/es-abstract#58]
If you check https://www.npmjs.com/package/es-abstract versions tab 1.14.0 is missing.

Due to that @vue/eslint-config-airbnb on latest machine fails to install on my local machine.
(I think others may fail as well)

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'frontend'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/henrique/.npm/_logs/2019-10-11T16_44_27_146Z-debug.log

Is there any particular reason for that?

Thanks :)

**Comment by henriquelbsouza** [comment]
Never mind, I fixed it deleting package-lock.json and it updated to 1.15.0.

:)

**Comment by ljharb** [comment]
Duplicate of #57. Duplicate of #56. Duplicate of #55.

**Comment by henriquelbsouza** [comment]
Yeah, sorry about that :)
