### ISSUE TITLE
Data files in `operations` folder are missing from v1.14 onwards

### ISSUE THREAD

**Issue by ExE-Boss** [ljharb/es-abstract#62]
This is a breaking change, since everything reachable is part of the public API.

I recommend keeping the `2015.js`, `2016.js`, `2017.js`, `2018.js` and `2019.js` files, which export useful data.

**Comment by ljharb** [comment]
That is true; the data was only intended for use by tests.

Other than your types PR, are you aware of anyone using the data? I’d prefer to consider it a bug that they were ever included, and I’d sooner bump to v2 than re-include them.

**Comment by ljharb** [comment]
Closing, pending more info.

**Comment by ExE-Boss** [comment]
Well, since you want to bump to v2 anyway, you should include the breaking changes from #67 and #68 with it.

**Comment by ljharb** [comment]
hmm, I'm actually confused. I npmignored the *js* files in `operations/`, not the json files. Those should be included still.

**Comment by ljharb** [comment]
ah lol they're all JS files. I think I intended to only block the scripts, not the data.
