### ISSUE TITLE
Removed 1.14.0 ver.

### ISSUE THREAD

**Issue by mdaljac** [ljharb/es-abstract#76]
Hi.

I developed project with 1.14.0 version, and this is: https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz in my package-lock. Today I run npm install and it shows some errors. I checked your .tgz and it says that it is not found. Can you please turn it back?

Thanks

**Comment by JakeChampion** [comment]
it can't be republished, you need to update your package-lock.json file

**Comment by ljharb** [comment]
Duplicate of #65, #60, #58, #57, #56, #55, #73.

From https://github.com/ljharb/es-abstract/issues/55#issuecomment-527707767
> Indeed, i apologize for the inconvenience - it hadn’t been 24 hours yet, and it had files in it that it shouldn’t have. v1.14.1 is already published, before i unpublished v1.14.0, so it should be trivial to update it in your lockfile.
