### ISSUE TITLE
Why are spackled scripts copies instead of aliases?

### ISSUE THREAD

**Issue by ExE-Boss** [ljharb/es-abstract#79]
The&nbsp;`spackle.js` script&nbsp;generates:
```js
'use strict';

module.exports = require('../<prevYear>/<opName>');
```

But&nbsp;the&nbsp;repository contains&nbsp;copies of&nbsp;the&nbsp;files.

**Comment by ljharb** [comment]
Aliases/symlinks behave differently platforms, but also require relative to themselves.

I changed it to use copies so a year’s operations would require sibling operations always from the current year.
