### ISSUE TITLE
1.17.0-next.1 version not able to install

### ISSUE THREAD

**Issue by slnkykrn** [ljharb/es-abstract#83]
With the latest version we got "No matching version found for es-abstract@1.17.0-next.1" while npm install operation. So we had to push package-lock.json files to server for now. When can it be again usable ?

**Comment by ljharb** [comment]
It's quite installable: https://unpkg.com/browse/es-abstract@1.17.0-next.1/

I'm not sure what issue you're having. Are you perhaps using a custom registry?

**Comment by slnkykrn** [comment]
We used custom registry , install packages from dregistry but if it can't find any packages it will go and download from npm package registry. What is the problem about using custom registry ?

**Comment by ljharb** [comment]
Apparently your custom registry only knows about versions under the "latest" dist-tag. The prerelease versions of v1.17.0 of this package are under the "next" tag.

This is your custom registry being broken - not this package and not the public registry.

**Comment by ljharb** [comment]
(Happy to reopen if there's something actionable here, but I can't conceive of what that would be)
