### ISSUE TITLE
Can't resolve './2015/AbstractEqualityComparison'

### ISSUE THREAD

**Issue by sujitwarrier11** [ljharb/es-abstract#86]
when ever I start my project I get the following error. Can't resolve './2015/AbstractEqualityComparison'
these files are not found 
1) AbstractEqualityComparison
2) AbstractRelationalComparison
3) StrictEqualityComparison

**Comment by ljharb** [comment]
They're quite present:
 - https://unpkg.com/browse/es-abstract@1.17.0/2015/AbstractEqualityComparison.js
 - https://unpkg.com/browse/es-abstract@1.17.0/2015/AbstractRelationalComparison.js
 - https://unpkg.com/browse/es-abstract@1.17.0/2015/StrictEqualityComparison.js

What version of es-abstract are you using? Are you using any sort of nonstandard settings? Do you get this error in node, in something like jest, or in a browser via a bundler?

**Comment by exsesx** [comment]
I have this problem, too. Just using ESLint (v 6.8.0), which extends the `react` and `standard` configurations.

**Comment by sujitwarrier11** [comment]
I deleted the node modules folder and did npm install and it worked for me.
closing this
